# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pypox Testing Workflow

on:
  push:
    branches:
      - development

permissions:
  contents: read-write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.6"
      - name: Install and update pip
        run: python -m pip install --upgrade pip
      - name: Install pipenv
        run: pip install pipenv
      - name: Install pipenv dependencies
        run: pipenv install
      - name: Install Pypox
        run: pipenv install pypox
      - name: Run pytest
        run: pipenv run pytest -s
