name: Test Python Package

on:
  push:
    branches:
      - development

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Use Pipx
        uses: CfirTsabari/actions-pipx@v1
      - name: Install dependencies
        run: |
          pipx install poetry
          poetry install
      - name: Test using pytest
        run: poetry run pytest
