name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current release version
        id: get_version
        run: echo "::set-output name=version::$(cat version.txt)"
      - name: Increment release version
        id: increment_version
        uses: actions/github-script@v4
        with:
          script: |
            const currentVersion = ${{ steps.get_version.outputs.version }};
            const versionParts = currentVersion.split('.');
            const newVersion = `${versionParts[0]}.${versionParts[1]}.${parseInt(versionParts[2]) + 1}`;
            console.log(`New version: ${newVersion}`);
            core.setOutput('new_version', newVersion);
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Add the repo scope to the GITHUB_TOKEN
          # This provides necessary permissions to access the resource
          permissions: repo
        with:
          tag_name: Pypox
          release_name: Release ${{ steps.increment_version.outputs.new_version }}
          body_path: CHANGELOG.md
          draft: true
          prerelease: true
